name: easyto-assets-common

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: make release-build VERSION=${{ inputs.version }}
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: _output/release/easyto-assets-build-*.tar.gz

  build-packer:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [darwin, linux, windows]
        exclude:
          - arch: arm64
            os: windows
    steps:
      - uses: actions/checkout@v4
      - run: make release-packer-one ARCH=${{ matrix.arch }} OS=${{ matrix.os }} VERSION=${{ inputs.version }}
      - uses: actions/upload-artifact@v4
        with:
          name: packer-${{ matrix.os }}-${{ matrix.arch }}
          path: _output/release/easyto-assets-packer-*.tar.gz

  build-runtime:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: make release-runtime VERSION=${{ inputs.version }}
      - uses: actions/upload-artifact@v4
        with:
          name: runtime
          path: _output/release/easyto-assets-runtime-*.tar.gz
