name: easyto
on: push
jobs:
  gen-version:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.run.outputs.version }}
    steps:
      - id: run
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
              echo "version=${GITHUB_REF_NAME}" >> ${GITHUB_OUTPUT}
              exit
          fi
          echo "version=v0.0.0-$(mktemp -u XXXXXXXX)" >> ${GITHUB_OUTPUT}
  build-packer:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [darwin, linux, windows]
        exclude:
          - arch: arm64
            os: windows
    needs:
      - gen-version
    steps:
      - uses: actions/checkout@v4
      - env:
          VERSION: ${{ needs.gen-version.outputs.version }}
        run: make release-packer-one ARCH=${{ matrix.arch }} OS=${{ matrix.os }} VERSION=${VERSION}
      - uses: actions/upload-artifact@v4
        with:
          name: packer-${{ matrix.os }}-${{ matrix.arch }}
          path: _output/release/easyto-assets-packer-*.tar.gz
  build-runtime:
    runs-on: ubuntu-24.04
    needs:
      - gen-version
    steps:
      - uses: actions/checkout@v4
      - env:
          VERSION: ${{ needs.gen-version.outputs.version }}
        run: make release-runtime VERSION=${VERSION}
      - uses: actions/upload-artifact@v4
        with:
          name: runtime
          path: _output/release/easyto-assets-runtime-*.tar.gz
  release:
    runs-on: ubuntu-24.04
    if: github.ref_type == 'tag'
    needs:
      - gen-version
      - build-packer
      - build-runtime
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - run: ls -R
      - uses: ncipollo/release-action@v1
        env:
          VERSION: ${{ needs.gen-version.outputs.version }}
        with:
          artifacts: artifacts/*.tar.gz
          commit: ${{ vars.GITHUB_SHA }}
          tag: ${{ env.VERSION }}
