name: easyto-assets-release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      version: ${{ github.ref_name }}

  release:
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRE_RELEASE: "${{ contains(github.ref_name, '-pre.') }}"
        with:
          args: artifacts/*.tar.gz
